"use client";

import { ImagePlus, Megaphone, Save } from "lucide-react";
import { useEffect, useState } from "react";

type AdSlot = { enabled: boolean; type: "image" | "adsense"; image_url: string; target_url: string; code: string };
type SlotKey = "header" | "article" | "sidebar";
const slots: Array<{ key: SlotKey; label: string; description: string }> = [{ key: "header", label: "إعلان الهيدر", description: "يظهر أعلى الموقع العام" }, { key: "article", label: "إعلان المقال", description: "يظهر داخل صفحات الأخبار" }, { key: "sidebar", label: "إعلان السايدبار", description: "يظهر في الشريط الجانبي" }];
const blank = (): AdSlot => ({ enabled: false, type: "image", image_url: "", target_url: "", code: "" });

export default function AdsPage() {
  const [ads, setAds] = useState<Record<SlotKey, AdSlot>>({ header: blank(), article: blank(), sidebar: blank() });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/settings", { cache: "no-store" }).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error); const stored = result.settings?.ads || {}; setAds({ header: { ...blank(), ...(stored.header || {}) }, article: { ...blank(), ...(stored.article || {}) }, sidebar: { ...blank(), ...(stored.sidebar || {}) } }); }).catch(reason => setError(reason instanceof Error ? reason.message : "تعذر تحميل الإعلانات")).finally(() => setLoading(false)); }, []);
  function update(key: SlotKey, patch: Partial<AdSlot>) { setAds(current => ({ ...current, [key]: { ...current[key], ...patch } })); }
  async function upload(key: SlotKey, file: File) { setError(""); const form = new FormData(); form.append("file", file); const response = await fetch("/api/media", { method: "POST", headers: { "x-upload-area": "ads" }, body: form }); const result = await response.json(); if (!response.ok) { setError(result.error || "تعذر رفع الصورة"); return; } update(key, { image_url: result.url, type: "image" }); }
  async function save() { setSaving(true); setMessage(""); setError(""); try { const response = await fetch("/api/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ ads }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage(result.message || "تم حفظ الإعلانات"); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر حفظ الإعلانات"); } finally { setSaving(false); } }
  if (loading) return <main className="min-h-screen p-6"><div className="mx-auto max-w-5xl animate-pulse rounded-xl border bg-card p-8">جاري تحميل الإعلانات...</div></main>;
  return <main className="min-h-screen flex-1 bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-5xl"><div className="mb-6"><p className="text-sm font-semibold text-primary">الإعلانات</p><h2 className="mt-1 text-2xl font-black">مساحات الإعلانات</h2><p className="mt-2 text-sm text-muted-foreground">كل بطاقة تحفظ مباشرة في إعدادات Supabase ويقرأها الموقع العام.</p></div>{message && <p role="status" className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}{error && <p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}<div className="grid gap-5 lg:grid-cols-3">{slots.map(slot => { const ad = ads[slot.key]; return <section key={slot.key} className="rounded-xl border bg-card p-5 shadow-sm"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-bold">{slot.label}</h3><p className="mt-1 text-xs text-muted-foreground">{slot.description}</p></div><button type="button" onClick={() => update(slot.key, { enabled: !ad.enabled })} aria-label={`تفعيل ${slot.label}`} className={`h-6 w-11 rounded-full p-1 ${ad.enabled ? "bg-primary" : "bg-muted"}`}><span className={`block size-4 rounded-full bg-white transition-transform ${ad.enabled ? "-translate-x-5" : ""}`} /></button></div><label className="text-xs font-bold">النوع<select value={ad.type} onChange={event => update(slot.key, { type: event.target.value as AdSlot["type"] })} className="admin-input mt-1.5 text-sm"><option value="image">صورة</option><option value="adsense">AdSense</option></select></label>{ad.type === "image" ? <><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed p-4 text-xs font-bold text-primary"><ImagePlus size={17} />{ad.image_url ? "تغيير الصورة" : "رفع صورة الإعلان"}<input type="file" accept="image/*" className="hidden" onChange={event => { const file = event.target.files?.[0]; if (file) void upload(slot.key, file); }} /></label><input dir="ltr" value={ad.target_url} onChange={event => update(slot.key, { target_url: event.target.value })} className="admin-input mt-3 text-xs" placeholder="رابط عند الضغط (اختياري)" />{ad.image_url && <img src={ad.image_url} alt="معاينة الإعلان" className="mt-3 h-24 w-full rounded-lg object-cover" />}</> : <textarea dir="ltr" value={ad.code} onChange={event => update(slot.key, { code: event.target.value })} className="admin-input mt-3 min-h-32 text-xs" placeholder="ألصق كود AdSense هنا" />}</section>; })}</div><button disabled={saving} onClick={save} className="interactive-button mt-6 flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60"><Save size={17} />{saving ? "جارٍ الحفظ..." : "حفظ كل الإعلانات"}</button></div></main>;
}
