"use client";

import { ExternalLink, FolderPlus, Tags } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

type Category = { id: number; name: string; slug: string; is_active: boolean };
const staticPages = [{ label: "عن الموقع", href: "/about" }, { label: "تواصل معنا", href: "/contact" }, { label: "سياسة الخصوصية", href: "/privacy" }, { label: "الشروط والأحكام", href: "/terms" }];

export default function CategoriesPage() {
  const [tab, setTab] = useState<"news" | "pages">("news"); const [categories, setCategories] = useState<Category[]>([]); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function fetchCategories() { const response = await fetch("/api/admin/categories", { cache: "no-store" }); const result = (await response.json().catch(() => ({}))) as { categories?: Category[]; error?: string }; if (!response.ok) throw new Error(result.error ?? "تعذر تحميل الأقسام"); return result.categories ?? []; }
  useEffect(() => { let active = true; fetchCategories().then(items => { if (active) setCategories(items); }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : "تعذر تحميل الأقسام"); }); return () => { active = false; }; }, []);
  async function addCategory() { if (!name.trim()) return; setBusy(true); setError(""); try { const response = await fetch("/api/admin/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim() }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "تعذر إضافة القسم"); setName(""); setCategories(await fetchCategories()); } catch (reason) { setError(reason instanceof Error ? reason.message : "تعذر إضافة القسم"); } finally { setBusy(false); } }
  async function toggleActive(category: Category) { setError(""); const response = await fetch("/api/admin/categories", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: category.id, is_active: !category.is_active }) }); const result = (await response.json().catch(() => ({}))) as { category?: Category; error?: string }; if (!response.ok || !result.category) { setError(result.error ?? "تعذر تغيير حالة القسم"); return; } setCategories(current => current.map(item => item.id === category.id ? result.category! : item)); }
  return <main className="min-h-screen flex-1 bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-4xl"><div className="mb-6"><p className="text-sm font-semibold text-primary">إدارة المحتوى</p><h2 className="mt-1 text-2xl font-black">الأقسام والصفحات</h2></div><div className="mb-5 flex w-fit gap-1 rounded-xl border bg-card p-1"><button onClick={() => setTab("news")} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === "news" ? "bg-accent text-primary" : "text-muted-foreground"}`}>أقسام إخبارية</button><button onClick={() => setTab("pages")} className={`rounded-lg px-4 py-2 text-sm font-bold ${tab === "pages" ? "bg-accent text-primary" : "text-muted-foreground"}`}>صفحات ثابتة</button></div>{error && <p role="alert" className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{tab === "news" ? <><section className="rounded-xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap gap-2"><input value={name} onChange={event => setName(event.target.value)} placeholder="اسم القسم الجديد" className="admin-input flex-1" /><button disabled={busy} onClick={addCategory} className="interactive-button flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground disabled:opacity-60"><FolderPlus size={17} />إضافة</button></div></section><section className="mt-5 overflow-hidden rounded-xl border bg-card shadow-sm"><table className="w-full text-right text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr><th className="p-4 font-semibold">القسم</th><th className="p-4 font-semibold">المعرف</th><th className="p-4 font-semibold">الحالة</th></tr></thead><tbody>{categories.length === 0 ? <tr><td colSpan={3} className="p-10 text-center text-muted-foreground"><Tags className="mx-auto mb-3" size={26} />لا توجد أقسام بعد</td></tr> : categories.map(category => <tr key={category.id} className="border-t hover:bg-muted/40"><td className="p-4 font-semibold">{category.name}</td><td className="p-4 font-mono text-xs text-muted-foreground" dir="ltr">{category.slug}</td><td className="p-4"><button onClick={() => void toggleActive(category)} className={`rounded-full px-3 py-1 text-xs font-bold ${category.is_active ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-600"}`}>{category.is_active ? "مفعل" : "متوقف"}</button></td></tr>)}</tbody></table></section></> : <section className="grid gap-4 sm:grid-cols-2">{staticPages.map(page => <Link key={page.href} href={page.href} target="_blank" className="flex items-center justify-between rounded-xl border bg-card p-5 shadow-sm transition hover:border-primary"><span><p className="font-bold">{page.label}</p><p className="mt-1 text-xs text-muted-foreground" dir="ltr">{page.href}</p></span><ExternalLink size={17} className="text-primary" /></Link>)}</section>}</div></main>;
}
