"use client";

import { Activity, Eye, FileCheck2, FilePlus2, FolderKanban, Radio, RefreshCw, Search, Settings2, ShieldCheck, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ThemeToggle } from "@/components/ThemeToggle";

type DashboardStats = { published: number; pending: number; views: string; live: number; categories: number; staff: number };
type DashboardData = { stats: DashboardStats; articles: { id: string; title: string; category: string; status: string; time: string }[]; live: { title: string; viewers: number }[] };
const defaultVisible = { published: true, pending: true, views: true, live: true, categories: true, staff: true };
const statItems = [
  { key: "published", label: "أخبار منشورة", icon: FileCheck2, tone: "text-emerald-600", accent: "from-emerald-400/25" },
  { key: "pending", label: "قيد المراجعة", icon: Activity, tone: "text-amber-600", accent: "from-amber-400/25" },
  { key: "categories", label: "أقسام نشطة", icon: FolderKanban, tone: "text-violet-600", accent: "from-violet-400/25" },
  { key: "staff", label: "أعضاء الفريق", icon: ShieldCheck, tone: "text-cyan-600", accent: "from-cyan-400/25" },
  { key: "views", label: "إجمالي المشاهدات", icon: Eye, tone: "text-sky-600", accent: "from-sky-400/25" },
  { key: "live", label: "بث مباشر الآن", icon: Radio, tone: "text-rose-600", accent: "from-rose-400/25" },
] as const;

export default function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState<string | null>(null); const [customizeOpen, setCustomizeOpen] = useState(false);
  const [visibleStats, setVisibleStats] = useState<Record<string, boolean>>(() => { if (typeof window === "undefined") return defaultVisible; try { return { ...defaultVisible, ...(JSON.parse(window.localStorage.getItem("dashboard-stats") || "null") || {}) }; } catch { return defaultVisible; } });
  useEffect(() => { let cancelled = false; fetch("/api/dashboard", { cache: "no-store" }).then(async response => { const result = await response.json() as DashboardData & { error?: string }; if (!response.ok) throw new Error(result.error || "تعذر تحميل بيانات اللوحة"); if (!cancelled) { setData(result); setLoadError(null); } }).catch(reason => { if (!cancelled) setLoadError(reason instanceof Error ? reason.message : "تعذر تحميل بيانات اللوحة"); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const toggleStat = (key: string) => setVisibleStats(current => { const next = { ...current, [key]: !current[key] }; window.localStorage.setItem("dashboard-stats", JSON.stringify(next)); return next; });
  const glass = "border border-white/60 bg-white/65 shadow-[0_20px_60px_rgba(15,23,42,0.08)] backdrop-blur-xl dark:border-white/10 dark:bg-white/[0.06] dark:shadow-black/20";
  return <main className="min-h-screen flex-1 bg-[radial-gradient(circle_at_top_right,rgba(13,124,134,0.13),transparent_34%),radial-gradient(circle_at_bottom_left,rgba(124,58,237,0.09),transparent_30%)] p-4 text-foreground sm:p-6 lg:p-8"><div className="mx-auto max-w-7xl animate-rise-in"><div className={`${glass} mb-6 flex flex-wrap items-center justify-between gap-4 rounded-[1.75rem] p-5 sm:p-7`}><div><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-primary">غرفة الأخبار الرقمية</p><h2 className="text-2xl font-black tracking-tight sm:text-4xl">مركز التحكم والبيانات</h2><p className="mt-2 text-sm text-muted-foreground">أرقام مباشرة من قاعدة البيانات، بلا تقديرات أو أرقام وهمية.</p></div><div className="flex items-center gap-2"><ThemeToggle /><button onClick={() => setCustomizeOpen(!customizeOpen)} className="interactive-button grid size-10 place-items-center rounded-xl border bg-white/50 text-muted-foreground dark:bg-white/5" aria-label="تخصيص اللوحة"><Settings2 size={17} /></button><Link href="/articles/new" className="interactive-button flex h-10 items-center gap-2 rounded-xl bg-primary px-3 text-sm font-bold text-primary-foreground"><FilePlus2 size={16} />خبر جديد</Link></div></div>
      {customizeOpen && <div className={`${glass} mb-5 flex flex-wrap items-center gap-3 rounded-2xl p-4 text-xs`}><span className="font-bold">إظهار الكروت:</span>{statItems.map(({ key, label }) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={visibleStats[key]} onChange={() => toggleStat(key)} />{label}</label>)}</div>}
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{statItems.filter(({ key }) => visibleStats[key]).map(({ key, label, icon: Icon, tone, accent }) => <div key={key} className={`${glass} interactive-card relative overflow-hidden rounded-2xl p-5`}><div className={`pointer-events-none absolute -left-6 -top-8 size-28 rounded-full bg-gradient-to-br ${accent} to-transparent blur-2xl`} /><div className="relative flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-2xl bg-white/70 ${tone} shadow-sm dark:bg-white/10`}><Icon size={20} /></span><TrendingUp size={16} className="text-primary/70" /></div><p className="relative mt-5 text-3xl font-black tracking-tight">{loading ? <span className="inline-block h-9 w-16 animate-pulse rounded-lg bg-muted" /> : data?.stats[key] ?? 0}</p><p className="relative mt-1 text-sm text-muted-foreground">{label}</p></div>)}</section>
      {loadError && <div role="alert" className="mt-5 rounded-2xl border border-rose-200 bg-rose-50/80 p-4 text-sm text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/30 dark:text-rose-200"><div className="flex flex-wrap items-center justify-between gap-3"><span>{loadError}</span><button type="button" onClick={() => window.location.reload()} className="rounded-lg bg-rose-700 px-3 py-2 text-xs font-bold text-white">إعادة المحاولة</button></div></div>}
      <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_340px]"><div className={`${glass} min-w-0 overflow-hidden rounded-2xl`}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/50 p-5 dark:border-white/10"><div><h2 className="font-bold">أحدث الأخبار</h2><p className="mt-1 text-xs text-muted-foreground">آخر المحتوى المضاف لغرفة الأخبار</p></div><div className="flex items-center gap-2 rounded-xl border border-white/60 bg-white/40 px-3 py-2 text-muted-foreground dark:border-white/10 dark:bg-white/5"><Search size={16} /><input className="w-24 bg-transparent text-xs outline-none sm:w-40" placeholder="بحث..." aria-label="بحث في الأخبار" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-white/30 text-xs text-muted-foreground dark:bg-white/5"><tr><th className="p-4 font-semibold">العنوان</th><th className="p-4 font-semibold">التصنيف</th><th className="p-4 font-semibold">الحالة</th><th className="p-4 font-semibold">التوقيت</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-10 text-center text-sm text-muted-foreground"><RefreshCw className="mx-auto mb-2 animate-spin" size={18} />جاري تحميل البيانات</td></tr> : data?.articles.map(article => <tr key={article.id} className="interactive-row border-t border-white/40 dark:border-white/10"><td className="max-w-sm p-4 font-semibold">{article.title}</td><td className="p-4 text-muted-foreground">{article.category}</td><td className="p-4"><span className="rounded-full bg-accent px-2.5 py-1 text-xs font-semibold text-primary">{article.status}</span></td><td className="p-4 text-xs text-muted-foreground">{article.time}</td></tr>)}</tbody></table></div></div><aside className={`${glass} rounded-2xl p-5`}><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">البث المباشر</h2><p className="mt-1 text-xs text-muted-foreground">حسب إعدادات الموقع الحالية</p></div><span className="flex items-center gap-1 text-xs font-bold text-rose-600"><span className="size-2 animate-pulse rounded-full bg-rose-600" /> مباشر</span></div><div className="space-y-3">{data?.live.length ? data.live.map(item => <div key={item.title} className="rounded-xl border border-white/50 bg-white/35 p-3 dark:border-white/10 dark:bg-white/5"><p className="text-sm font-bold">{item.title}</p><p className="mt-2 flex items-center gap-1 text-xs text-muted-foreground"><Eye size={14} /> {item.viewers} مشاهد مسجل</p></div>) : <p className="rounded-xl bg-muted/50 p-4 text-center text-sm text-muted-foreground">لا يوجد بث نشط حاليًا</p>}</div></aside></section></div></main>;
}
