"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";

type RequestItem = { id: string; user_id: string; status: "pending" | "approved" | "rejected"; rejection_reason?: string | null; created_at: string; email: string; profiles?: { full_name?: string } | null };
export default function PasswordResetRequestsManager() {
  const [items, setItems] = useState<RequestItem[]>([]); const [busy, setBusy] = useState("");
  async function load() { const session = (await createClient().auth.getSession()).data.session; const response = await fetch("/api/admin/password-reset-requests", { headers: { Authorization: `Bearer ${session?.access_token ?? ""}` }, cache: "no-store" }); if (response.ok) setItems(await response.json()); }
  useEffect(() => { void load(); }, []);
  async function review(item: RequestItem, status: "approved" | "rejected") { const reason = status === "rejected" ? window.prompt("اكتب سبب رفض الطلب") : ""; if (status === "rejected" && !reason) return; setBusy(item.id); const session = (await createClient().auth.getSession()).data.session; await fetch("/api/admin/password-reset-requests", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session?.access_token ?? ""}` }, body: JSON.stringify({ id: item.id, status, reason }) }); setBusy(""); await load(); }
  return <section className="glass-card p-6"><div className="mb-6"><h1 className="text-2xl font-bold">طلبات كلمة السر</h1><p className="mt-2 text-sm opacity-70">راجع طلبات الموظفين ووافق عليها أو ارفضها مع توضيح السبب.</p></div><div className="overflow-x-auto"><table className="w-full text-right text-sm"><thead><tr className="border-b border-glass-border/40"><th className="p-3">الموظف</th><th className="p-3">البريد</th><th className="p-3">التاريخ</th><th className="p-3">الحالة</th><th className="p-3">إجراء</th></tr></thead><tbody>{items.map((item) => <tr key={item.id} className="border-b border-glass-border/20"><td className="p-3">{item.profiles?.full_name ?? "-"}</td><td className="p-3" dir="ltr">{item.email}</td><td className="p-3">{new Date(item.created_at).toLocaleDateString("ar-EG")}</td><td className="p-3">{item.status === "pending" ? "قيد المراجعة" : item.status === "approved" ? "تمت الموافقة" : `مرفوض: ${item.rejection_reason ?? ""}`}</td><td className="p-3">{item.status === "pending" && <span className="flex gap-2"><button disabled={busy === item.id} onClick={() => void review(item, "approved")} className="rounded-lg bg-emerald-600 px-3 py-2 text-white">موافقة</button><button disabled={busy === item.id} onClick={() => void review(item, "rejected")} className="rounded-lg bg-red-600 px-3 py-2 text-white">رفض</button></span>}</td></tr>)}</tbody></table>{items.length === 0 && <p className="p-8 text-center opacity-60">لا توجد طلبات كلمة سر.</p>}</div></section>;
}
